### ISSUE TITLE
Cannot specify a default index pattern

### ISSUE THREAD

**Issue by jahshuah** [elastic/stack-docker#15]
Left default of `logstash-*` in as the pattern, `@timestamp` as the Time Filter Field Name, clicked "Create", clicked star to set as default index, and the default index pattern refuses to save. Clicking on any other navigation item ("Discover" for example) returns me to the management page to define a default index pattern.

At this point, I cannot get past this element. `docker-compose up -d` and login via `http://localhost:5601` is as far as I can get.

Thanks.

**Comment by nayluge** [comment]
Same issue here.

I tried to load a sample dataset but it's not working neither.

The only strange thing i can see in logs is a redirect to login just after the request:
```
kibana_1            | {"type":"response","@timestamp":"2017-11-14T22:00:57Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"kibana:5601","user-agent":"Go-http-client/1.1","connection":"close"},"remoteAddress":"172.19.0.13","userAgent":"172.19.0.13"},"res":{"statusCode":302,"responseTime":3,"contentLength":9},"message":"GET / 302 3ms - 9.0B"}
```

**Comment by xeraa** [comment]
`logstash-*` is the default Kibana pattern, but do we really create such an index?

Can you run a `GET _cat/indices` in Console or the equivalent cURL command with your credentials and try with one of the available indices?

**Comment by nayluge** [comment]
Actually i tried on a new indice ( the shakespare's one as documented on the how-to ) and it's not working on the last revision.

I've pulled the 5.6 branch and it's working. 
Imo, there's an issue with auth on the master branch

**Comment by jahshuah** [comment]
`GET _cat/indices` results in:

```
yellow open logstash-2017.11.15               LDCWwW2CQSKBk6CwBohszQ 5 1   45   0 152.1kb 152.1kb
yellow open .kibana                           ZVaDz_jiQJe8qMEhPwuaAg 5 1  319  17 910.6kb 910.6kb
yellow open .monitoring-kibana-6-2017.11.15   MdB5YEWwSxmwz-Sb809BOA 1 1   24   0    68kb    68kb
yellow open auditbeat-6.0.0-2017.11.15        LdyApT1-Rsu38lDZNOTSaA 5 1    6   0  63.1kb  63.1kb
yellow open heartbeat-6.0.0-2017.11.15        g7_KbJLMRWCZX38ootTeDg 5 1  200   0 375.3kb 375.3kb
yellow open .monitoring-es-6-2017.11.15       Q0D3u_e0RdmM1CGQsFtYsA 1 1  596 375 597.2kb 597.2kb
green  open .security-6                       yE9nXBBUT5W8KKUfaj5Pig 1 0    1   0   3.6kb   3.6kb
yellow open .monitoring-alerts-6              RBK6Sv2WQ_qO7l8EXSftHA 1 1    1   0   6.5kb   6.5kb
yellow open metricbeat-6.0.0-2017.11.15       00Qa1-HGQoWCk5U2XuziuQ 5 1  361   0 359.4kb 359.4kb
yellow open .watcher-history-6-2017.11.15     fBCH3MY2RhyCQ_LTkKpOvQ 1 1   21   0  61.4kb  61.4kb
yellow open packetbeat-6.0.0-2017.11.15       nJW1XZ7JQCS5d5QjUY--Pw 5 1 7316   0   2.8mb   2.8mb
yellow open .triggered_watches                Q9edUWSZTiiMcBhVQPMcow 1 1    0   0    233b    233b
yellow open .watches                          eumnNuO5TlWsezKb_axzqg 1 1    5   0  15.9kb  15.9kb
yellow open .monitoring-logstash-6-2017.11.15 ZXovWzElTrmvG0C95K_jJg 1 1   90   0 117.2kb 117.2kb
```

**Comment by jarpy** [comment]
Thanks for this report. I think it's fixed in e41680ed7d61856dc46e2eb1383c6924b07ac0b4.

Before that change, Kibana was connecting to Elasticsearch as the `elastic` user. It's now connecting as the `kibana` user, which must have its password provisioned before it will work.

I suspect that `elastic` lost certain privileges between the `rc2` and `GA` releases.

cc @dliappis & @michaelbaamonde as this is likely to affect `kibana-docker` beyond the context of `stack-docker`. The image uses the `elastic` user by default, for ease of use, but that now appears to be a bug.

**Comment by arussellsaw** [comment]
i'm on the latest build and i'm still unable to save an index pattern

**Comment by arussellsaw** [comment]
i destroyed my stack and changed the elastic user password when i recreated, seems to work now. not sure why.

**Comment by cpower** [comment]
Same issue here

**Comment by mbarretta** [comment]
same

**Comment by ampcode666** [comment]
Still happening here too.

**Comment by dliappis** [comment]
I have also been able to reproduce this, by logging in to http://localhost:5601 using the `kibana` user, but, interestingly enough, I can set a default index pattern if I login using the `elastic` user instead (same password as the kibana user, [defined here](https://github.com/elastic/stack-docker/blob/master/.env#L3)).

**Comment by mbarretta** [comment]
I removed all the containers and tried again, this time success. Maybe there is some kind of race condition in there somewhere?

**Comment by jarpy** [comment]
@dliappis: The `kibana` user is not intended to be used for interactive login, it's strictly a back-end, system user. I wish it was called `kibana_system` instead.

@mbarretta: Is it possible you had some state in the Elasticsearch containers? If anyone can reproduce this with `docker-compose down -v && docker-compose up` then we still have a problem. If not, we can close this out.

**Comment by xeraa** [comment]
@MarxDimitri ran into that issue today (checked out today's version), but I couldn't reproduce it. Not sure how to make sure if it's really gone unfortunately...

**Comment by cmg-dev** [comment]
@mbarretta I did the same thing:

1. removed all containers
1. removes all images

But the issue persists.

I can confirm, the issue, with the `kibana` user.
Using the `elastic` user, the issue is different.

**Comment by cmg-dev** [comment]
**OS**

**Docker**

```bash
docker -v
Docker version 17.09.0-ce, build afdb6d4

docker-compose -v
docker-compose version 1.16.1, build 6d1ac21
```

**images**

```
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
docker.elastic.co/logstash/logstash                      6.0.0               a521dea276d8        2 weeks ago         647MB
docker.elastic.co/kibana/kibana                          6.0.0               2f0aebda029e        2 weeks ago         727MB
docker.elastic.co/elasticsearch/elasticsearch-platinum   6.0.0               0a0ea46be626        2 weeks ago         537MB
docker.elastic.co/beats/packetbeat                       6.0.0               478b111e47cb        2 weeks ago         414MB
docker.elastic.co/beats/metricbeat                       6.0.0               bc8ff400feac        2 weeks ago         474MB
docker.elastic.co/beats/heartbeat                        6.0.0               49f6694ede15        2 weeks ago         390MB
docker.elastic.co/beats/filebeat                         6.0.0               c308079a66bb        2 weeks ago         348MB
docker.elastic.co/beats/auditbeat                        6.0.0               715f0e23049e        2 weeks ago         345MB
centos                                                   7                   d123f4e55e12        3 weeks ago         197MB
```

**Steps to reproduce:**

1. Clone this Repostory
1. Run `docker-compose up`
1. Login to `localhost:5601`; use the user `kibana` or use the user `elastic`
1. See the issue with the Default Index Pattern

**Comment by dliappis** [comment]
> Using the elastic user, the issue is different.

@cmg-dev So you are supposed to login with the `elastic` user; the `kibana` user is a system-only user needed by Kibana. Is it so that you can't specify the default index pattern also when using the `elastic` user?

**Comment by cmg-dev** [comment]
@dliappis 

Thanks for your reply;  I checked this; here is what I found:

1. Firstly, the `elastic` users gave me access to the preconfigured index pattern.

1. Then I found @jarpy 's comment above. https://github.com/elastic/stack-docker/issues/15#issuecomment-346185157

1. I used `docker-compose down -v` and then `docker-compose up` again.

1. The result was the same faulty behaviour.

   <img width="1388" alt="bildschirmfoto 2017-11-27 um 10 57 02" src="https://user-images.githubusercontent.com/4034128/33261144-2d2b425a-d362-11e7-96f7-eac230bb46c3.png">

   As you can see, there are NO index pattern preconfigured after this.

1. I tried this now 10 times `compose-down`/`compose-up`
1. 9 of them gave the me same error

**Comment by dliappis** [comment]
@cmg-dev reg. your point 1. and 2. above, yes as corroborated by @jarpy 's comment, it is the `elastic` user that needs to be used for logging into kibana. The `kibana` user is a system user, used internally by kibana but not to be used by interactive users.

You shouldn't be having the problem described in 4. when you use the `elastic` user, regardless of the amount of `compose-down`/`compose-up` attempts.

**Comment by cmg-dev** [comment]
Okay, I narrowed it down to this `docker-compose.yml`:

```yaml
---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    environment:
      - 'xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}'
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks: ['stack']
    depends_on: ['elasticsearch', 'setup_logstash']

  setup_logstash:
    image: centos:7
    volumes: ['./scripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro']
    # The script may have CR/LF line endings if using Docker for Windows, so
    # make sure that they don't confuse Bash.
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-logstash.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['stack']
    depends_on: ['elasticsearch']

  setup_kibana:
    image: centos:7
    volumes: ['./scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['stack']
    depends_on: ['elasticsearch']

networks: {stack: {}}
```

This only uses `kibana`, `logstash`, `elastic` without any fancy Beats.

**I found out that**

It now works reliable; I can create default index pattern; I use the elastic user; tried this 10 times now.

**How I proceed** 

I will now add the the Beats; try to find out, when stuff will break. :)
