### ISSUE TITLE
Allow easy way to specify a data directory

### ISSUE THREAD

**Issue by HonzaKral** [elastic/stack-docker#46]
Primary use case, for me, is to be able to run integration tests against the cluster created by `stack-docker`. Unfortunately the built-in filesystem is too slow so I would like to have it mounter to `/tmp` on the host machine which is running `tmpfs`

**Comment by fxdgear** [comment]
@HonzaKral if you wanna use tmpfs you can by specifying the driver_opts in the `es_data` volume: 

```yml
volumes:
  es_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
```

Will this work for ya?
